"use client"
import './globals.css'
import StateContext from '@/context/context'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <StateContext>
        <main className="flex w-full max-w-screen-xl min-h-screen flex-col justify-between overflow-x-hidden">{children}</main>
      </StateContext>
      </body>
      
    </html>
  )
}
